Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "id"
          "AttributeType": "S"
        - "AttributeName": "name"
          "AttributeType": "S"
        - "AttributeName": "email"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "users"


#   aws cloudformation create-stack --stack-name lambda-table --template-body file://LambdaExampleTable.yml --capabilities CAPABILITY_IAM   // Example
#   aws cloudformation create-stack --stack-name users --template-body file://UsersTable.yml --capabilities CAPABILITY_IAM
